services:
  - type: web
    name: criptoya-like-mvp
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: "/health"
    autoDeploy: true
